name: Release

on:
  create:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: tagged-release
    runs-on: ubuntu-latest
    steps:
      - name: Set Tag Variable
        run: echo "tag=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Gradle
        run: ./gradlew build -Pmod_version="${{ env.tag }}"
      - name: create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/libs/*