name: tagmaker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          # have to use a personal access token here in order to trigger the release workflow
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
